### ISSUE TITLE
Why are You not including the "Content" folder?

### ISSUE THREAD

**Issue by farahjr** [MOZGIII/ue5-gitignore#4]
At least here in my project, "content" is the main folder with assets I use, but since I'm new at this, just wondering if You are not including content folder how do You handle this with the rest of the team:

**Comment by MOZGIII** [comment]
See https://github.com/MOZGIII/ue5-gitignore#content:

> Game assets in Unreal Engine formats, .uasset and .umap. Only those two file types are allowed, everything else is ignored.

Thus content directory is handled, but only `.umap` and `.uproject` are allowed.

**Comment by farahjr** [comment]
So how people usually handle the content folder? How you source control it if not by git? Do you use a second source control/repository?

Right now I'm suing git with azure and got some issues with size going over 10GB due some Para on assets. Now I'm submoduling those Third part assets from content and tried your ignore and attributes, but got the warning when trying to create the sub module índice content folder that git ignore would ignore the git module files. 

So I was wondering if I'm doing something unprofessional here.

**Comment by MOZGIII** [comment]
People just have their `.uasset` and `.umap` files at the `Content` directory, cause everything there is just either `.uasset` or `.umap`. That's it - and it's all we need to keep in git.
For anything else, like raw texture or model files, there is a `RawContent` directory.

You should also use git-lfs and a proper git host that can handle git-lfs with locking with good upload/download speed. In some cases using git (with or without lfs) becomes a burden - it will take ~twice the space on the disk of what's the repo content because of how git internally handles copies of data. You might be better off using SVN if have issues with git in your project, or P4 if you're or with using proprietary software.

**Comment by farahjr** [comment]
> 

Really? That's strange because when downloading Paragon assets they got straight to Content/ParagonCharacterName and it raises a LOT of issues if I try to move from that folder. That's why I thought content folder was supposed to be backed up.
Yes I'm using lfs, each paragon character is 2GB I don't plan changing them so I don't this will be one an issue in the future.

Also Azure+,Git was the best free tier solution I was able to come up with, have asked in many FB groupsbut no one had a free option that doesn't involve hosting it my self. It's just me and my cousin.

**Comment by farahjr** [comment]
Sorry, You were right, I didn't checked the folder's content, i didn't knew there was only unreal type files. I got confused by the git warning:

The following paths are ignored by one of your .gitignore files:
Content/ParagonSerath
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"


I just runned the command again with -f, I was afraid there could be somethings being ignored. but I think you need to not ignore git files inside content, otherwise can't use git modules anywhere:

![image](https://user-images.githubusercontent.com/27826334/183779875-0ad843de-27ea-48be-a5d6-3f110e098eff.png)

**Comment by farahjr** [comment]
NVM the module creation worked just fine. Thanks!
